# Directory to store uploaded images (can be absolute path)
# If left empty, it will default to: {user.home}/swp_uploads/
upload.dir=F:/SWP/swp_uploads

# Base URL to access uploaded files
# If left empty, it will default to: {contextPath}/uploads/
upload.baseurl=
